### ISSUE TITLE
Message multi ligne

### ISSUE THREAD

**Issue by Yann151924** [Mineaurion/AurionChat-AutoMessage#1]
Permettre un message multiligne ou quelque chose de similaire.

En adaptant la configuration dans ce format on devrait pouvoir faire quelque chose :

```YAML
announcements:
  #You can use it for based language announcement for example
  auto-fr:
    - - "Annonce 1 ligne 1"
      -  " Annonce 1 ligne 2"
    - "Annonce 2"
  auto-en:
    - - "Annonce 1 en ligne 1"
      - "Annonce 1 en ligne 2"
    - "Annonce 2 en"
```
